export default {
    SEND_VERIFICATION_CODE_SUCCESSFULLY: 'SEND_VERIFICATION_CODE_SUCCESSFULLY',
    SEND_VERIFICATION_CODE_LOADING: 'SEND_VERIFICATION_CODE_LOADING',
    SEND_VERIFICATION_CODE_REJECT: 'SEND_VERIFICATION_CODE_REJECT',
    SEND_VERIFICATION_CODE_FAILED: 'SEND_VERIFICATION_CODE_FAILED',


    VALIDATE_VERIFICATION_CODE_SUCCESSFULLY: 'VALIDATE_VERIFICATION_CODE_SUCCESSFULLY',
    VALIDATE_VERIFICATION_CODE_LOADING: 'VALIDATE_VERIFICATION_CODE_LOADING',
    VALIDATE_VERIFICATION_CODE_REJECT: 'VALIDATE_VERIFICATION_CODE_REJECT',
    VALIDATE_VERIFICATION_CODE_FAILED: 'VALIDATE_VERIFICATION_CODE_FAILED',
}